### ISSUE TITLE
Provide update site for the mondo-integration target platform definition

### ISSUE THREAD

**Issue by agarciadom** [atlanmod/ATL_MR#7] opened 2015-08-06 15:15 UTC
Within the MONDO integration repository, we have a branch dedicated to integrating CloudATL into the management server. This branch depends on ATL/MR, so we would like to add ATL/MR to the our target platform definition. In order to do that, we'd need ATL/MR to have an update site uploaded somewhere.

**Comment by abelgomez** [comment] 2015-08-06 15:27
This issue is a duplicate of mondo-project/mondo-integration#1

**Closed as completed by abelgomez** 2015-08-06 15:27 UTC
Labels: enhancement
